### PR TITLE
0.25.0-rc1: add Nitrokey Start and Pro 2 test results

### PR DESCRIPTION
**Pull request by alt3r-3go**
As discussed in https://github.com/OpenSC/OpenSC/issues/3017, here are the basic testing results (`pkcs11-tool --login --test`) for Nitrokey Start and Pro 2 (full output below for completeness).

Start seems to have a problem at the very last step (thus "many tests passed" and not "all"), but this was present before the changes for 0.25.0-rc1 went in (`master` as of at least a month or so ago). I plan to look into this later, after I update the token to the latest FW (RTM.13), which I'm having some troubles with at the moment.

```console
# Nitrokey Start
[user@host dir]$ ./install/bin/pkcs11-tool --module=./install/lib/opensc-pkcs11.so --test --login --pin <removed>
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  RIPEMD160: OK
  SHA-1: OK
  SHA256: OK
Ciphers: not implemented
Signatures (currently only for RSA)
  testing key 0 (Encryption key)  -- can't be used for signature, skipping
  testing key 1 (Authentication key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (Encryption key) -- can't be used to sign/verify, skipping
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (Encryption key)
    RSA-PKCS: OK
  testing key 1 (Authentication key)
error: PKCS11 function C_Decrypt failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
    RSA-PKCS: [user@host dir]$ 

# Nitrokey Pro 2
[user@host dir]$ ./install/bin/pkcs11-tool --module=./install/lib/opensc-pkcs11.so --test --login --pin <removed>
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  RIPEMD160: OK
  SHA-1: OK
  SHA256: OK
Ciphers: not implemented
Signatures (currently only for RSA)
  testing key 0 (Encryption key)  -- can't be used for signature, skipping
  testing key 1 (Authentication key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (Encryption key) -- can't be used to sign/verify, skipping
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (Encryption key)
    RSA-PKCS: OK
  testing key 1 (Authentication key)
    RSA-PKCS: OK
No errors
```

### CODE REVIEW

**Comment by dengert** [comment]
>  error: PKCS11 function C_Decrypt failed: rv = CKR_GENERAL_ERROR (0x5)

can be fixed with  https://github.com/OpenSC/OpenSC/commit/1b95de4014f851eeeee5e3a4f2a803a187209c8a
which is part of a much larger set  changes in https://github.com/OpenSC/OpenSC/compare/master...X25519-improvements-2

**Comment by dengert** [comment]
>  @dengert can you submit this commit as separate PR so it can be merged for the next rc?
will do.

**Comment by Jakuje** [comment]
> I see [2f9ab4d](https://github.com/OpenSC/Wiki/commit/2f9ab4d313980f5451ae7e607358ed07c655cb88) was merged in the meanwhile, and it also mentions Nitrokey Start, although without FW version. Should I remove the Start from this PR, or maybe @xhanulik could qualify currently committed result with a version too (I can add it in this PR while rebasing)?

Sorry for a delay. We had larger bunch of cards tested including the Nitrokey start  so please, rebase on top of current changes so we can merge your testing results too. Feel free to add the FW version of your nitrokey start too.

**Comment by Jakuje** [comment]
Than you. Looks good. I will leave it up to @xhanulik to merge and update the main repository.

**Comment by xhanulik** [comment]
> I also took the liberty of fixing a whitespace error + changing the "NitroKey" to "Nitrokey", as that's what they use as the name all over the NK documentation and marketing materials.

Thank you, merging.

**Pull request merged**
